### ISSUE TITLE
Support for alternative slack autocomplete syntax

### ISSUE THREAD

**Issue by cakejelly** [dblock/slack-ruby-bot#17]
I just noticed this when following your Mathbot tutorial. `@mathbot: calculate` works but `mathbot: calculate` doesn't.

The syntax for the second command can be a result of slacks autocomplete (unless you switch it off) and you need to explicitly add it as an alias to get it working. Can we support this by default?

**Comment by dblock** [comment]
I believe I had implemented this in https://github.com/dblock/slack-ruby-bot/commit/80e2321eef35e6bf464b262867f43e6c2098160b, but haven't updated mathbot. Can you please try this with HEAD of slack-ruby-bot on mathbot to confirm? I can release 0.4.4 shortly if that works.

**Comment by cakejelly** [comment]
80e2321 allows you to address your bot via `@<botname>`... but if you begin typing your bots name without '@' and press tab, the following text will be entered: `<botname>: `.This isn't picked up as a valid alias. Instead, it recognises `<botname>` as the alias and treats everything else as your command, resulting in `Sorry @cakejelly, I don't understand that command!`

Currently i'm using the following as a workaround:

```
SlackRubyBot.configure do |config|
  config.aliases = ['mathbot:']
end
```

I only took a brief look at the code, but I think adding `"#{user}:"` to  `names` (https://github.com/dblock/slack-ruby-bot/blob/master/lib/slack-ruby-bot/config.rb#L13) could solve this

**Comment by dblock** [comment]
Yep, do you want to try a PR with a test?

**Comment by cakejelly** [comment]
Yeah will do :) Will try get one up later on.

**Comment by dblock** [comment]
Implemented in https://github.com/dblock/slack-ruby-bot/commit/715ff28f7a998f961aa5f55c64eae7bf0f7b86d3.
