### ISSUE TITLE
Bot listening to HTTP requests?

### ISSUE THREAD

**Issue by skatkov** [dblock/slack-ruby-bot#20]
I think about building a development supporting service that gathers key data and bot that will act as a middleman between this all. I've had a glance on examples and through bot code, and noticed that bot is listening only messages via websocket. I've seen sinatra used with example bots you provided, but didn't notice any cooperation between them :)

How could I do http call that will trigger bot to output something in channel?

**Comment by dblock** [comment]
You mean via webhook? That doesn't really require any infratructure, so no need for slack-ruby-bot, you can see an example in https://github.com/dzucconi/emojify. 

If you do think something can make things easier here, feel free to reopen an issue.
