### ISSUE TITLE
what is the proper way to send attachments?

### ISSUE THREAD

**Issue by gconklin** [dblock/slack-ruby-bot#25]
From a command, what is the proper way to send an attachment (https://api.slack.com/docs/attachments) ?

I've tried:

`send_message( client, data.channel, message, attachments: [{ fallback: "fb", pretext: "pt", title: "the title", text: "some text" }]  )`

I also tried:

`client.web_client.chat_postMessage( channel: data.channel, text: message, attachments: [{ fallback: "fb", pretext: "pt", title: "the title", text: "some text" }] )`

But it just sends what is in `message` and no fancy stuff.

```
$ bundle list |grep ruby
  * slack-ruby-bot (0.4.5)
  * slack-ruby-client (0.3.1)
```

Thanks!

**Comment by dblock** [comment]
The RealTime client doesn't support attachments, from https://api.slack.com/rtm:

<img width="680" alt="screenshot 2015-11-05 06 58 14" src="https://cloud.githubusercontent.com/assets/542335/10967733/a50a3de6-838a-11e5-9d3a-d1331009eec8.png">

However the web client should allow you to do that. I tried and it didn't work, then I found https://github.com/slackhq/node-slack-client/issues/12. You need to `to_json` the attachments property. 

Now the canonical example works:

```
.chat_postMessage(
  channel: ...,
  text: 'Hello World',
  as_user: true,
  attachments: [
        {
            fallback: "New ticket from Andrea Lee - Ticket #1943: Can't rest my password - https://groove.hq/path/to/ticket/1943",
            pretext: "New ticket from Andrea Lee",
            title: "Ticket #1943: Can't reset my password",
            title_link: "https://groove.hq/path/to/ticket/1943",
            text: "Help! I tried to reset my password but nothing happened!",
            color: "#7CD197"
        }
    ].to_json
```

I think slack-ruby-client should do this for you, I opened https://github.com/dblock/slack-ruby-client/issues/20.

**Comment by gconklin** [comment]
Yep! That worked, thanks for digging that up. I've been using your framework for a few months now and it has saved me a bunch of time. Thanks!
