### ISSUE TITLE
How to send message from bot without command from user

### ISSUE THREAD

**Issue by WojciechKo** [dblock/slack-ruby-bot#31]
I'm making bot that informs you about weather every day at 8am.
How can I send message with ruby code, not as response to user command?

**Comment by dblock** [comment]
This framework is primarily about responding in RealTime, for what you want to do just use slack-ruby-client, see https://github.com/dblock/slack-ruby-client#web-client.

```ruby
client = Slack::Web::Client.new
client.auth_test
client.chat_postMessage(channel: '#general', text: 'Hello World', as_user: true)
```
