### ISSUE TITLE
Support sending messages as_user: true

### ISSUE THREAD

**Issue by dblock** [dblock/slack-ruby-bot#4]
https://github.com/cjwooo/mafiabot seems to be using `chat_postMessage` because it wants `as_user: true`.

**Comment by zachfeldman** [comment]
Sooooo this commit just messed me up pretty majorly when I tried to change `as_user` to false and there was no warning that the attr wasn't being passed correctly. Maybe we can allow people to pass in an option for that? I'll be forking and patching for my use case...

**Comment by zachfeldman** [comment]
Sorry I didn't mean to sound that upset! Wanted to clarify that this gem has been SUPER HELPFUL and I really appreciate your work @dblock :D. I think we don't say that enough on here.

**Comment by zachfeldman** [comment]
Hmm also maybe I'm wrong about the above because this is a pretty old commit and now I can't find as_user anywhere important...

**Comment by zachfeldman** [comment]
Ok so if anyone is at all curious, I was trying to set as_user using the rtm methods and not the web client methods. You can't do this. Trying to find a solution for my problem with RTM, which is to set a bot icon.

**Comment by dblock** [comment]
I don't think you can @zachfeldman, the message in RTM doesn't allow you to specify `as_user`. But you can use the web client to send anything `as_user` though under an RTM bot.

**Comment by zachfeldman** [comment]
You're right. If you are creating a vendored bot (what I'm doing) you can set a default icon that gets used across teams!
