### ISSUE TITLE
Keyboard typing "..." when sending a message

### ISSUE THREAD

**Issue by luisbebop** [dblock/slack-ruby-bot#55]
I implemented a command that takes few seconds to respond to the user.
How can I simulate the keyboard typing "..." ?

Thanks in advance.

**Comment by dblock** [comment]
You can do this with `client.typing(channel: '#channel')`, it sends something like `{ type: 'typing', id: 42, channel: 'channel' }` to the web socket. See https://github.com/dblock/slack-ruby-client/blob/fcdc4b1c90df51ce14cf85480e0de47f9a2bc1a9/lib/slack/real_time/api/typing.rb#L10. There's an example [here](https://github.com/dblock/slack-ruby-client/blob/e4c39604b6d00da1e419d63db68e30032f5a08e1/examples/hi_real_time_async/hi.rb#L17). 

Note, if you're going to take some time to respond to user messages, you probably want to do the operation async.
