### ISSUE TITLE
Using slack ruby client commands

### ISSUE THREAD

**Issue by maxbrodi** [dblock/slack-ruby-bot#61]
Hi,

Thanks a lot for the amazing gem.
Unfortunately I can't use slack ruby client commands with it such as:
- client.channels_list.channels
or
- client.channels_info(channel: '#general')

I get a "undefined method `channels_info' for #<SlackRubyBot::Client:0x007fb2e1624030>" error each time. Am I doing something wrong here?

Thank you

**Comment by maxbrodi** [comment]
What I'm trying to do is to send private messages to users instead of posting in a channel, I guess that using these kind of functions to get the users' ID is the best way.

**Comment by dblock** [comment]
You want the Web client that was used to obtain the RealTime connection in the first place, try this:

```ruby
client.web_client.channels_list
```

Maybe the doc could use some updating, please feel free to PR.

**Comment by dblock** [comment]
Btw, this is documented in the RealTime client itself, but that's not part of this gem - https://github.com/dblock/slack-ruby-client#combining-realtime-and-web-clients.
