### ISSUE TITLE
chat_postMessage ignores fields in attachments?

### ISSUE THREAD

**Issue by ncorrare** [dblock/slack-ruby-bot#64]
Hey There,
According to the Slack API I should be able to use fields (https://api.slack.com/docs/attachments)

I tried the following code and it doesn't work:
.chat_postMessage(
                channel: data.channel,
                as_user: true,
                attachments: [
                  {
                  fallback: "List couldn't be displayed",
                  title: "Latest Jobs",
                  fields: '[
                    {
                    title: "ID"
                    value: "1"
                    short: "true"
                    },
                    {
                    title: "ID"
                    value: "1"
                    short: "true"
                    }
                  ]',
                  color: '#82C045'
                  }
                ].to_json
              )

Am I missing something. Apparently it never goes through the API either:
Faye::WebSocket::API::MessageEvent, {"type":"message","user":"XXXXXXXX","text":"","attachments":[{"fallback":"List couldn't be displayed","title":"Latest Jobs","id":1,"color":"82C045"}],"channel":"C0NG9JDTL","ts":"XXXXXXXXXXX"}

**Comment by ncorrare** [comment]
I just noticed this is probably better suited on slack-api-ref or slack-ruby-client..., but as far as I could tell from the code that parameter is not valid/considered within attachments...

**Comment by dblock** [comment]
Yes this belongs in slack-ruby-client, I'll close it here. Before you reopen it there, check whether the data is being sent to Slack (I don't see why it wouldn't). If it is, then it's something on slack side, but I would confirm with `curl` and open a ticket with them. Also you don't need to call `to_json` when using slack-ruby-client btw.
