### ISSUE TITLE
How can I get a list of the users in a channel within a matcher?

### ISSUE THREAD

**Issue by jbyauk** [dblock/slack-ruby-bot#67]
Suppose I have a matcher in a subclass of SlackRubyBot::Bot. I'm trying to do something like the following:
```
match /^something$/ do |client, data, match|
  # do something with match

  client.channels[data.channel].users.values.each do |user|
    # do something for each user in the channel
  end
end
```

I essentially would like to perform some operation looping over the list of users in the channel from which I received the message which matched my matcher, but I'm not sure how to get that list of users.

**Comment by wuzzzzaah** [comment]
@jbyauk try this
```
client.web_client.channels_info(channel: data.channel)
```

you should get a channel info result set, with users as an array of IDs inside.

**Comment by dblock** [comment]
With the default store (`Slack::RealTime::Stores::Store`) you get all channels in `store.channels` and you get the channel users in there as `members` as well, plus the client will keep them up-to-date for you as changes come in. This will be a lot more efficient.

I'll close this, please reopen/comment if you have any other questions.

**Comment by jbyauk** [comment]
Thank you, I appreciate it!
