### ISSUE TITLE
how can i override server instance to register my own `star_added` hook?

### ISSUE THREAD

**Issue by movstox** [dblock/slack-ruby-bot#70]
hi all,

i was following https://github.com/dblock/slack-ruby-bot/blob/master/TUTORIAL.md
and read the readme on hooks.

though, i can't figure out how (at what point of tutorial mentioned above) can i obtain `server` instance or how to force bot to use `MyServer` so I can register own hooks?

sorry, looks like very simple question. many thanks.

p.s. i've tried this:
```ruby
module SlackFbrunbot
  class Bot < SlackRubyBot::Bot
    def self.instance
      SlackFbrunbot::MyServer.instance
    end
  end
end
```

```ruby
module SlackFbrunbot
  class MyServer < SlackRubyBot::Server
    on 'hello' do |client, data|
      logger.info 'heloooo'
      # data['user']['id'] contains the user ID
      # data['user']['name'] contains the new user name
    end
  end
end
```

on `rackup` getting 

`undefined method 'on' for SlackFbrunbot::MyServer:Class (NoMethodError)`

**Comment by dblock** [comment]
Are you using HEAD? That feature is in 0.8.0 that hasn't shipped yet, but soon.

**Comment by movstox** [comment]
Let me try HEAD, still not sure how to override the server.

**Comment by dblock** [comment]
You're doing it right, I have a working example in https://github.com/dblock/slack-amber-alert/blob/master/slack-bot-server/server.rb. I'll close this for now, reopen if you see more issues.
