### ISSUE TITLE
Example using oauth tokens?

### ISSUE THREAD

**Issue by leei** [dblock/slack-ruby-bot#71]
We're integrating with slack on a per-user/per-team basis with oauth tokens. We get back a user-specific token and a team-specific token.  We use the team-specific token to send messages with a bot id. I want to create a bot using slack-ruby-bot within this framework.

I see that you can start a generic server with `SlackRubyBot::Server.new(token: bot_token)` but then how does the server know which subclass of SlackRubyBot::Bot to handle messages with? I'm assuming I'll need one bot per Team that at least one of my oauthed users is authenticated against and I'll use the team-specific token to run that server.

**Comment by dblock** [comment]
Correct. The storage and web parts are not part of this project, but a full example is in https://github.com/dblock/slack-bot-server. You might also want to watch a video where I live code a slack bot service for multiple teams ;) - http://code.dblock.org/2016/03/11/your-first-slack-bot-service-video.html

I'll close this, hope it helps!
