### ISSUE TITLE
Possible to send unescaped text (to support <http://...|text of link>

### ISSUE THREAD

**Issue by billdueber** [dblock/slack-ruby-bot#73]
I'm looking, and I can't figure out where I might be able to do this. Pointer?

**Comment by dblock** [comment]
It's just text, what have you tried so far?

**Comment by billdueber** [comment]
Boy, was that a crappy issue. My apologies. 

Based on [this page](https://api.slack.com/docs/formatting), I expected text of the form:

```
<http://billdueber.com|bill dueber>
```
...to render as a link from the text "bill dueber". However, despite the big section at the bottom talking about how to format messages in your slack clients, it appears that the official slack clients don't do anything about the tagged text in terms of formatting, in in either the browser or the mac "app", whether sent by my bot or typed right in by me. 

So, that's disappointing, but not the problem of your gem, which I'm thoroughly enjoying. Thanks for all your work!

**Comment by dblock** [comment]
If you use `chat_postMessage`, that renders as you expect. Working code:

```
require 'slack-ruby-client'

Slack.configure do |config|
  config.token = ENV['SLACK_API_TOKEN']
end

client = Slack::Web::Client.new

client.chat_postMessage(channel: '#general', text: 'click <http://code.dblock.org|here>', as_user: true)
```

<img width="280" alt="screen shot 2016-05-11 at 8 33 04 pm" src="https://cloud.githubusercontent.com/assets/542335/15200763/aafa1bd8-17b7-11e6-9df4-a553652b6552.png">

If you use `say` (or `message` in the lower level API), it only supports a limited subset of that. The doc at https://api.slack.com/rtm is totally unclear about this (I couldn't find what the limitations are other than attachments, which clearly isn't true), so I suggest opening a help ticket about this, they will definitely correct it. It renders users, but not links.

<img width="375" alt="screen shot 2016-05-11 at 8 42 09 pm" src="https://cloud.githubusercontent.com/assets/542335/15200849/de70a602-17b8-11e6-9e5c-d8c5cc418073.png">

In slack-ruby-bot you can do client.web_client.chat_postMessage, it's slower but it will do what you want.

**Comment by m5rk** [comment]
Yes, the Slack docs on what formatting works in which API commands is unclear. They refer to "default message formatting" but that page discusses more than "default message formatting" so the limits of "default message formatting" are uncertain (to me at least).

I solved this using the good old strategy of indirection. When I `say`, instead of calling this gem's `say`, I use my own `say`:
```ruby
    def say(text)
      return unless bot?

      slack_message_sender.say(data.channel, text)
    end
```

which in turn calls this method:
```ruby
  def say(channel, text)
    return unless enabled_for_direct_message?

    message = {
      as_user: true,
      channel: channel,
      text: text
    }

    client.chat_postMessage(message)
  end
```

The `client` there is simply:

```ruby
  def client
    @client ||= Slack::Web::Client.new(token: slack_token.bot_access_token)
  end
```

This Just Works™.

**Comment by m5rk** [comment]
I submitted an issue to Slack about this and got this response:

> The Real Time API does not support formatted links — the RTM was designed for fast, lightweight plain text chat messages only (https://api.slack.com/rtm#formatting_messages).
> 
> The Web API (chat.postMessage — api.slack.com/methods/chat.postMessage) and Incoming webhooks support link formatting.
> 

I followed up:

> Would you be able to update the documentation to include your very unambiguous and clear statement?
> 
> https://api.slack.com/rtm#formatting_messages
> 
> Currently, that section is not clear about whether formatted links are supported. It says:
> 
> The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes. To post a more complex message as a user clients can call the chat.postMessage Web API method with as_user set to true.
> 
> The default message formatting page includes a section on formatting URLs.
> 
> This is what led to my assumption that the RTM API supports formatted links.

And I got this response:

> Fair point — I'll ask the team to clarify the docs, I agree with your assessment!
