### ISSUE TITLE
How should I call start_async on Rails?

### ISSUE THREAD

**Issue by torneco** [dblock/slack-ruby-bot#74]
I'm stuck with implementing ruby-slack-bot on rails for starting multiple bots.
Like [this](https://github.com/dblock/slack-bot-server/blob/master/config.ru#L17), I run `bundle exec rails runner bin/slack_bot_server.rb` with below code, but it didn't run at all.

```ruby
# bin/slack_bot_server.rb
SlackBotServer::Service.instance.start_from_database!
```

Could you give me a hint for starting ruby-slack-bot on Rails?
Thank you

**Comment by dblock** [comment]
In Rails you can start the server the same way in `config.ru`. If you look at [the implementation of `start_from_database!`](https://github.com/dblock/slack-bot-server/blob/8796147338c7ae6e8dc21ddc71b815867204526f/slack-bot-server/service.rb#L37), it ends up calling [start_async](https://github.com/dblock/slack-bot-server/blob/8796147338c7ae6e8dc21ddc71b815867204526f/slack-bot-server/service.rb#L45) which doesn't block.

**Comment by dblock** [comment]
Share some more code if you can't get it to work! I'll close this for now.

**Comment by torneco** [comment]
Thanks for reply!
I could start slack-ruby-bot on Rails with `config.ru`!

If possible I want to manage separately Rails and slack-ruby-bot, but below codes didn't work. Do you have any idea?

Thanks

#### Gemfile

```ruby
gem 'slack-ruby-bot', '~> 0.8.0'
gem 'celluloid-io', require: ['celluloid/current', 'celluloid/io']
```

#### Procfile

```ruby
slack_server: bundle exec rails runner bin/slack_server
web: bundle exec rails server
```

#### bin/slack_server

```ruby
SlackBotServer::App.instance.prepare!

Thread.abort_on_exception = true

Thread.new do
  SlacklBotServer::Service.start_from_database!
end
```

#### lib/slack-bot-server/app.rb

same as https://github.com/dblock/slack-bot-server/blob/master/slack-bot-server/app.rb

#### lib/slack-bot-server/service.rb

same as https://github.com/dblock/slack-bot-server/blob/master/slack-bot-server/service.rb

#### lib/slack-bot-server/server.rb

same as https://github.com/dblock/slack-bot-server/blob/master/slack-bot-server/server.rb

**Comment by dblock** [comment]
Define "doesn't work"?

Generally if you want your rails app to be also the registration for teams you're going to need a mechanism of telling the bot that a new team has been registered (they run in separate processes).

**Comment by dblock** [comment]
If the problem is `bundle exec rails runner bin/slack_server`, try `bundle exec ruby bin/slack_server`

**Comment by torneco** [comment]
Thanks again for your reply!

> Define "doesn't work"?

Sorry for not explaining enough. I mean it doesn't start, throwing no error.

```
➜  testbot git:(master) ✗ bundle exec rails runner bin/slack_server.rb
I, [2016-05-25T11:10:28.532585 #10687]  INFO -- : Starting team #<Team:0x007feeaa789fb0>.
I, [2016-05-25T11:10:28.564831 #10687]  INFO -- : post https://slack.com/api/rtm.start
D, [2016-05-25T11:10:28.564899 #10687] DEBUG -- request: Accept: "application/json; charset=utf-8"
User-Agent: "Slack Ruby Client/0.7.3"
Content-Type: "application/x-www-form-urlencoded"
➜  testbot git:(master) ✗ 
```

So I tried to comment out `Thread.new` block and call `bundle exec rails runner bin/slack_server.rb`, got messages below;

```ruby
# bin/slack_server.rb

SlackBotServer::App.instance.prepare!

# Thread.abort_on_exception = true

# Thread.new do
SlacklBotServer::Service.start_from_database!
# end
```

```
➜  testbot git:(master) ✗ bundle exec rails runner bin/slack_server.rb
I, [2016-05-25T10:43:02.193632 #9548]  INFO -- : Starting team #<Team:0x007f9aaaa0e230>.
I, [2016-05-25T10:43:02.235586 #9548]  INFO -- : post https://slack.com/api/rtm.start
D, [2016-05-25T10:43:02.235661 #9548] DEBUG -- request: Accept: "application/json; charset=utf-8"
User-Agent: "Slack Ruby Client/0.7.3"
Content-Type: "application/x-www-form-urlencoded"
I, [2016-05-25T10:43:03.218362 #9548]  INFO -- Status: 200
D, [2016-05-25T10:43:03.218459 #9548] DEBUG -- response: content-type: "application/json; charset=utf-8"
transfer-encoding: "chunked"
connection: "close"
access-control-allow-origin: "*"
cache-control: "private, no-cache, no-store, must-revalidate"
content-security-policy: "referrer no-referrer;"
date: "Wed, 25 May 2016 01:43:02 GMT"
expires: "Mon, 26 Jul 1997 05:00:00 GMT"
pragma: "no-cache"
server: "Apache"
strict-transport-security: "max-age=31536000; includeSubDomains; preload"
vary: "Accept-Encoding"
x-accepted-oauth-scopes: "rtm:stream,client"
x-content-type-options: "nosniff"
x-oauth-scopes: "identify,bot:basic"
x-xss-protection: "0"
x-cache: "Miss from cloudfront"
via: "1.1 f960dafcb3c8e2a2fc983a4e6653ee56.cloudfront.net (CloudFront)"
x-amz-cf-id: "8sf-oAkSs55E6a3ns878rZ1XeEFry3Fh_dLegM7TVhNtOCBkeaDCXg=="
D, [2016-05-25T10:43:03.233625 #9548] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#connect!: WebSocket::Driver::Client
➜  testbot git:(master) ✗ 
```

> If the problem is bundle exec rails runner bin/slack_server, try bundle exec ruby bin/slack_server

It depends on ActiveRecord for [this](https://github.com/dblock/slack-bot-server/blob/master/slack-bot-server/service.rb#L38), I need to exec with rails runner...

Thank you

**Comment by dblock** [comment]
Your program just terminates, it doesn't block on anything and by its end a bunch of connections are being opened while it exits. All this starts asynchronously, something has to block forever. In a mixed example with Rails you have a web server waiting for connections, and in your you want this:

```ruby
loop do
  Thread.pass
end
```

**Comment by torneco** [comment]
It works! ✨ 
Thank you for taking the time! 🙏
