### ISSUE TITLE
Infinity error when app disabled

### ISSUE THREAD

**Issue by SlayerShadow** [dblock/slack-ruby-bot#76]
When any team disables/removes application after releasing a bot, it produces `Slack::Web::Api::Error` with `account_inactive` message on logs. After that, server tries to reconnect, which produces the same error, and it is endless.
I found at `/lib/slack-ruby-bot/server.rb:94` potential problem which in fact infinitely restart server without the checking of incoming error type.

**Comment by dblock** [comment]
Indeed, this is a bug (or non-feature). 

In slack-bot-server I patched restart to go through https://github.com/dblock/slack-bot-server/blob/aed0283a97aaf4c6e9a331099c678288708860ae/slack-bot-server/service.rb#L43 which would disable the service. 

I'd like something here that addresses this problem and maybe invokes a callback like "disabled".

**Comment by SlayerShadow** [comment]
Thanks! I tried to change this current restart method, and it works.
In your example, why did not you include condition to `restart!` method? I mean, `@async ? start_async : start!` is conveniently for testing. I use `start_async` for development mode and `start!` command for production, and it could be unexpected behaviour in case of error if bot will be restarted with async mode on production.

**Comment by dblock** [comment]
I think that would be a sensible change @SlayerShadow, feel free to PR.

**Comment by SlayerShadow** [comment]
Thanks. This is my first pull request, so sorry if something went wrong. :)
