### ISSUE TITLE
Message hook is not working

### ISSUE THREAD

**Issue by andreasantillana** [dblock/slack-ruby-bot#83]
I have a bot that responds to commands without its name at the beginning ("I spent ..."), but only in DM, I have it on a private channel and it only responds to commands if its name is at the beginning ("bot I spent..."). Isn't the Message hook responsible for handling this scenario or should I do something else?

**Comment by dblock** [comment]
The message hook should be able to handle this. You can see the default implementation [here](https://github.com/dblock/slack-ruby-bot/blob/master/lib/slack-ruby-bot/hooks/message.rb#L4) that does quite involved things, but if you roll your own with `on :message` on the client it will do whatever you want. Maybe share some code?

**Comment by dblock** [comment]
Another way to do this is with `scan ...` which doesn't care about prefixes.

**Comment by andreasantillana** [comment]
I tried writing my message hook based on yours, still didn't respond to it. `scan` is working for me, I will go with it for now, but in the future I'll search deeper to find out what's going on with message hook.

Thanks a lot! 😄

**Comment by dblock** [comment]
Yes, please, I'd like a repro of the issue. I'll close this for now.
