### ISSUE TITLE
Username data data[:user][:name] does not exist.

### ISSUE THREAD

**Issue by brylor** [dblock/slack-ruby-bot#87]
Hi.

I'd like to get the username that ran a command or match, although when I look at data I only have a user field which shows a different than what I have in my slack profile...

```
From: /Users/a525544/Development/superbot/superbot.rb @ line 89 :

    84: 	items.where(:system => system).delete
    85: 	client.say(channel:data.channel, text: system.concat(" has been deleted"))
    86: end
    87:
    88: match /show user/i do |client,data,match|
 => 89: 	binding.pry
    91: #	system = match[:system]
    92: #	items = DB[:reservations]
    93: #	items.where(:system => system).delete
    94: #	client.say(channel:data.channel, text: system.concat(" has been deleted"))

[1] pry(SuperBot)> data
=> {"type"=>"message",
 "channel"=>"D1REXXXXX",
 "user"=>"U0JRXXXXX",
 "text"=>"show user",
 "ts"=>"5555555555.000129",
 "team"=>"555555555"}
```

**Comment by brylor** [comment]
I figured out I had to:

```
client.say(channel:data.channel, text: "<@".concat(data[:user]).concat(">") )
```

This is correct usage?

**Comment by dblock** [comment]
That's correct, the user ID is in the `user` field, you can render it as a username by making it a slack mention this way. If you actually want the user name, you can look it up in the local store or by a query, something like `client.store.users.detect { |user| user['id'] == ... }`. This actually could use a good example in https://github.com/dblock/slack-ruby-client, feel free to contribute.

I'll close this.

**Comment by jonmchan** [comment]
This works for me to get the actual user name:

`client.store.users[data.user]['name']`

eg.
```
  command 'whoami' do |client, data, match|
    client.say(text: "You are: #{data.user} <#{client.store.users[data.user]['name']}>", channel: data.channel)
  end
```
